# Generated by Django 5.1.7 on 2025-06-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_event_legaltemplate_toolkitresource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationproject',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
