# Generated by Django 5.1.7 on 2025-08-25 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_collaborationproject_link'),
        ('landingPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualdev',
            name='mail',
        ),
        migrations.AddField(
            model_name='individualdev',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_devs', to='landingPage.signupuser'),
        ),
    ]
