# Generated by Django 5.1.7 on 2025-08-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_individualdev_mail_individualdev_user'),
        ('landingPage', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='individualdev',
            constraint=models.UniqueConstraint(fields=('user', 'id_number'), name='unique_user_id_number'),
        ),
    ]
