# Generated by Django 5.1.7 on 2025-08-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_individualdev_unique_user_id_number'),
        ('landingPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='individualdev',
            name='unique_user_id_number',
        ),
        migrations.AddConstraint(
            model_name='individualdev',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_id_number'),
        ),
    ]
