# Generated by Django 5.1.7 on 2025-08-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_individualdev_unique_user_id_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='individualdev',
            name='unique_user_id_number',
        ),
        migrations.AddField(
            model_name='individualdev',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
