# Generated by Django 5.1.7 on 2025-08-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_individualdev_unique_user_id_number_and_more'),
        ('landingPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualdev',
            name='mail',
        ),
        migrations.AddConstraint(
            model_name='individualdev',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_id_number'),
        ),
    ]
