# Generated by Django 5.1.7 on 2025-08-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_individualdev_mail_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='individualdev',
            name='unique_user_id_number',
        ),
    ]
