# Generated by Django 5.1.7 on 2025-08-25 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_individualdev_unique_user_id_number'),
        ('landingPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualdev',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dev_profiles', to='landingPage.signupuser'),
        ),
    ]
